# Generated by Django 5.2 on 2026-07-23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0008_jobevaluationrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_key", models.CharField(max_length=80)),
                ("provider_label", models.CharField(max_length=160)),
                ("provider_version", models.CharField(max_length=100)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual search"),
                            ("scheduled", "Scheduled search"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("query_payload", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("new_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("outside_preference_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider_key", "-created_at"],
                        name="disc_run_provider_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="disc_run_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RawJobOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_key", models.CharField(max_length=80)),
                ("provider_label", models.CharField(max_length=160)),
                ("provider_version", models.CharField(max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                (
                    "normalized_source_url",
                    models.URLField(blank=True, max_length=1000),
                ),
                ("title_hint", models.CharField(blank=True, max_length=300)),
                ("company_hint", models.CharField(blank=True, max_length=300)),
                ("location_hint", models.CharField(blank=True, max_length=300)),
                (
                    "employment_type_hint",
                    models.CharField(blank=True, max_length=80),
                ),
                (
                    "work_arrangement_hint",
                    models.CharField(blank=True, max_length=80),
                ),
                ("industry_hint", models.CharField(blank=True, max_length=200)),
                ("seniority_hint", models.CharField(blank=True, max_length=100)),
                ("raw_listing_text", models.TextField()),
                ("raw_text_sha256", models.CharField(max_length=64)),
                ("role_identity_sha256", models.CharField(blank=True, max_length=64)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                (
                    "broad_relevance",
                    models.CharField(
                        choices=[
                            ("broad_match", "Broad preference match"),
                            ("unknown", "Not enough information"),
                            ("outside", "Outside broad preferences"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "broad_relevance_reasons",
                    models.JSONField(blank=True, default=list),
                ),
                ("duplicate_details", models.JSONField(blank=True, default=list)),
                ("duplicate_override", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("duplicate", "Duplicate"),
                            ("ready", "Ready for processing"),
                            ("ignored", "Ignored"),
                            ("sent_to_processing", "Sent to processing"),
                            ("processed", "Processed"),
                            ("processing_failed", "Processing failed"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("processing_error", models.TextField(blank=True)),
                ("discovered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_to_processing_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_duplicates",
                        to="tracker.jobposting",
                    ),
                ),
                (
                    "duplicate_of_opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rediscoveries",
                        to="job_discovery.rawjobopportunity",
                    ),
                ),
                (
                    "processed_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_sources",
                        to="tracker.jobposting",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="job_discovery.discoveryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-discovered_at"],
                        name="disc_opp_status_idx",
                    ),
                    models.Index(
                        fields=["provider_key", "external_id"],
                        name="disc_opp_provider_idx",
                    ),
                    models.Index(
                        fields=["normalized_source_url"],
                        name="disc_opp_url_idx",
                    ),
                    models.Index(
                        fields=["raw_text_sha256"],
                        name="disc_opp_text_idx",
                    ),
                ],
            },
        ),
    ]
