# Generated by Django 5.2.16 on 2026-07-23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_discovery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveryrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("partial", "Partially completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rawjobopportunity",
            name="source_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawjobopportunity",
            name="source_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rawjobopportunity",
            name="source_last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="rawjobopportunity",
            index=models.Index(
                fields=["provider_key", "source_is_active"],
                name="disc_opp_active_idx",
            ),
        ),
        migrations.CreateModel(
            name="DiscoverySourceAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=100)),
                ("source_label", models.CharField(max_length=200)),
                ("source_identifier", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("elapsed_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_attempts",
                        to="job_discovery.discoveryrun",
                    ),
                ),
            ],
            options={
                "ordering": ["source_label", "source_key"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="disc_source_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "source_key"),
                        name="disc_source_run_key_unique",
                    )
                ],
            },
        ),
    ]
