from django.test import TestCase, override_settings
from django.urls import reverse

from .intake_views import INTAKE_SESSION_KEY
from .models import JobPosting, JobRequirement
from .services.job_extraction import (
    ERROR_CONFIGURATION,
    BaseJobExtractor,
    JobExtractionError,
    JobExtractionRequest,
    JobExtractionResult,
    extract_job,
    get_job_extractor,
)
from .services.job_intake import DeterministicJobExtractor, PARSER_VERSION


SIMPLE_LISTING = """
Job Title: Biomedical Test Engineer
Company: Example Medical
Location: Boston, MA

Required Qualifications
- Bachelor's degree in Biomedical Engineering
- Python
"""


class FakeJobExtractor(BaseJobExtractor):
    provider_key = "fake"
    provider_label = "Fake test extractor"
    provider_version = "fake-v1"
    extraction_mode = "test"

    def extract(self, request: JobExtractionRequest) -> JobExtractionResult:
        return self.result(
            job={
                "title": "AI Draft Title",
                "company": "Provider Company",
                "job_url": request.source_url,
                "source": request.source_label,
                "description": request.listing_text,
            },
            requirements={
                "role_family": "Biomedical Engineering",
                "required_skills": "Python",
            },
            evidence=["Generated by the fake provider."],
            warnings=["Human review is still required."],
        )


class UnsafeJobExtractor(BaseJobExtractor):
    provider_key = "unsafe"
    provider_label = "Unsafe test extractor"
    provider_version = "unsafe-v1"
    extraction_mode = "test"

    def extract(self, request: JobExtractionRequest) -> JobExtractionResult:
        return self.result(
            job={"title": {"not", "session", "safe"}},
            requirements={},
        )


class ExtractionProviderContractTests(TestCase):
    def test_default_provider_is_the_deterministic_parser(self):
        extractor = get_job_extractor()

        self.assertIsInstance(extractor, DeterministicJobExtractor)
        self.assertEqual(extractor.provider_version, PARSER_VERSION)

    def test_standard_result_contains_provider_metadata_and_complete_shapes(self):
        result = extract_job(
            SIMPLE_LISTING,
            source_url="https://example.com/jobs/test-engineer",
            source_label="Company website",
        )

        self.assertEqual(result["provider"]["key"], "deterministic")
        self.assertEqual(result["provider"]["version"], PARSER_VERSION)
        self.assertEqual(result["parser_version"], PARSER_VERSION)
        self.assertEqual(result["job"]["title"], "Biomedical Test Engineer")
        self.assertIn("next_action", result["job"])
        self.assertIn("certifications", result["requirements"])
        self.assertIn("minimum_years_experience", result["requirements"])

    @override_settings(
        JOB_INTAKE_EXTRACTOR=(
            "tracker.test_job_extraction_provider.FakeJobExtractor"
        )
    )
    def test_intake_view_uses_the_configured_provider_without_saving_a_job(self):
        response = self.client.post(
            reverse("job_intake_start"),
            {
                "raw_text": SIMPLE_LISTING,
                "source_url": "https://example.com/jobs/test-engineer",
                "source_label": "Company website",
            },
        )

        self.assertRedirects(response, reverse("job_intake_review"))
        self.assertEqual(JobPosting.objects.count(), 0)
        draft = self.client.session[INTAKE_SESSION_KEY]
        self.assertEqual(draft["extraction"]["provider"]["key"], "fake")
        self.assertEqual(draft["extraction"]["job"]["title"], "AI Draft Title")
        self.assertFalse(draft["extraction"]["orchestration"]["fallback_used"])

        review = self.client.get(reverse("job_intake_review"))
        self.assertContains(review, "FAKE TEST EXTRACTOR")
        self.assertContains(review, "FAKE-V1")
        self.assertContains(review, "No job has been created yet")

    @override_settings(
        JOB_INTAKE_EXTRACTOR="tracker.models.JobPosting",
        JOB_INTAKE_FALLBACK_ENABLED=True,
        JOB_INTAKE_FALLBACK_EXTRACTOR=(
            "tracker.services.job_intake.DeterministicJobExtractor"
        ),
    )
    def test_invalid_primary_configuration_uses_disclosed_fallback(self):
        response = self.client.post(
            reverse("job_intake_start"),
            {"raw_text": SIMPLE_LISTING},
        )

        self.assertRedirects(response, reverse("job_intake_review"))
        draft = self.client.session[INTAKE_SESSION_KEY]
        extraction = draft["extraction"]
        self.assertEqual(extraction["provider"]["key"], "deterministic")
        self.assertTrue(extraction["orchestration"]["fallback_used"])
        self.assertEqual(
            extraction["orchestration"]["attempts"][0]["error_category"],
            ERROR_CONFIGURATION,
        )
        self.assertEqual(JobPosting.objects.count(), 0)

        review = self.client.get(reverse("job_intake_review"))
        self.assertContains(review, "FALLBACK USED")
        self.assertContains(review, "CONFIGURATION")

    def test_non_serializable_provider_output_is_rejected(self):
        with self.assertRaises(JobExtractionError):
            extract_job(SIMPLE_LISTING, extractor=UnsafeJobExtractor())

    def test_empty_listing_is_rejected_before_provider_execution(self):
        with self.assertRaises(JobExtractionError):
            extract_job("   ", extractor=FakeJobExtractor())

    def test_provider_can_supply_partial_fields_and_receive_safe_defaults(self):
        result = extract_job(SIMPLE_LISTING, extractor=FakeJobExtractor())

        self.assertEqual(result["job"]["employment_type"], "unknown")
        self.assertEqual(result["job"]["deadline_status"], "unknown")
        self.assertEqual(
            result["requirements"]["seniority_level"],
            JobRequirement.SeniorityLevel.UNKNOWN,
        )
        self.assertEqual(
            result["job"]["next_action"],
            "Verify listing and review requirements",
        )
