# Generated by Django 5.2.16 on 2026-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='next_action',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('saved', 'Saved'), ('preparing', 'Preparing application'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='discovered', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_arrangement',
            field=models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
